In [1]:
import pandas as pd
import numpy as np
import os

import difflib
import unidecode

from datetime import datetime
import locale

## Union datos sociodemogr√°ficos Madrid con geo
La idea es obtener un CSV con el CSV formateado y con una columna que sea el id de geo de la zona correspondiente.

In [2]:
data_sociodem = pd.read_csv("./barrios_sociodem.csv")
data_sociodem.head()

,dem_CodBarrio,dem_Barrio,dem_PobTotal,dem_NumViviendas,dem_TamanoMedioDelHogar,dem_TasaDeParo,dem_PropSinEstudios,dem_PropSinEstudiosUniversitarios,dem_PropConEstudiosUniversitarios,dem_Densidad_(Habit/Ha),dem_EdadMedia,dem_Indice_de_juventud,dem_Indice_de_dependencia,dem_Indice_de_estructura_de_la_poblacion_activa,dem_Indice_de_reemplazo_de_la_poblacion_activa,dem_Proporcion_de_nacidos_fuera_de_Espana,geo_barrio
0,11,Palacio,23593,11583.0,2.036864,10.309215,0.095704,0.391468,0.512828,160.506857,45.781100,41.233620,36.045439,85.139319,32.591623,26.278981,Palacio
1,12,Embajadores,47048,22564.0,2.085091,10.658808,0.135393,0.430405,0.434202,455.131010,42.694610,60.804723,28.206665,108.044674,38.643068,36.554157,Embajadores
2,13,Cortes,10771,5449.0,1.976693,8.076921,0.074405,0.368364,0.557231,181.981221,44.779547,42.699115,31.497986,96.426859,28.985507,34.026553,Cortes
3,14,Justicia,18021,8856.0,2.034892,8.017261,0.065683,0.360603,0.573714,243.720022,44.090422,50.194553,30.823956,96.589125,40.457256,31.219133,Justicia
4,15,Universidad,33418,16913.0,1.975877,9.006094,0.083812,0.386598,0.529590,352.500616,43.678945,47.996165,30.031128,108.875163,34.142306,32.102460,Universidad

In [3]:
data_geo = pd.read_csv("./geo_elements.csv")
data_geo.head()

,id,name,st_astext,level_id
0,1,Madrid,"MULTIPOLYGON(((-3.88557654999994 40.57445562,-...",1
1,2,Villaverde,MULTIPOLYGON(((-3.70366015928759 40.3635648718...,2
2,3,Villa de Vallecas,MULTIPOLYGON(((-3.60705428494233 40.3866622239...,2
3,34,Gaztambide,MULTIPOLYGON(((-3.71111051636411 40.4389285909...,3
4,4,Usera,MULTIPOLYGON(((-3.68974605859619 40.3823311367...,2

In [4]:
# Comprobamos cuantos elementos tiene cada uno
data_geo = data_geo[data_geo.level_id == 3] 
len(data_geo.name.unique())

131

In [5]:
len(data_sociodem.geo_barrio.unique())

131

In [6]:
def get_geo_id(name):
    try:
        return data_geo[data_geo.name == name].id.values[0]
    except:
        print(name)

# Intentamos machear directamente por nombre, sin difflib
data_sociodem["geo_id"] = data_sociodem["geo_barrio"].apply(lambda x: get_geo_id(x))
data_sociodem.head()

nan

,dem_CodBarrio,dem_Barrio,dem_PobTotal,dem_NumViviendas,dem_TamanoMedioDelHogar,dem_TasaDeParo,dem_PropSinEstudios,dem_PropSinEstudiosUniversitarios,dem_PropConEstudiosUniversitarios,dem_Densidad_(Habit/Ha),dem_EdadMedia,dem_Indice_de_juventud,dem_Indice_de_dependencia,dem_Indice_de_estructura_de_la_poblacion_activa,dem_Indice_de_reemplazo_de_la_poblacion_activa,dem_Proporcion_de_nacidos_fuera_de_Espana,geo_barrio,geo_id
0,11,Palacio,23593,11583.0,2.036864,10.309215,0.095704,0.391468,0.512828,160.506857,45.781100,41.233620,36.045439,85.139319,32.591623,26.278981,Palacio,139.0
1,12,Embajadores,47048,22564.0,2.085091,10.658808,0.135393,0.430405,0.434202,455.131010,42.694610,60.804723,28.206665,108.044674,38.643068,36.554157,Embajadores,124.0
2,13,Cortes,10771,5449.0,1.976693,8.076921,0.074405,0.368364,0.557231,181.981221,44.779547,42.699115,31.497986,96.426859,28.985507,34.026553,Cortes,135.0
3,14,Justicia,18021,8856.0,2.034892,8.017261,0.065683,0.360603,0.573714,243.720022,44.090422,50.194553,30.823956,96.589125,40.457256,31.219133,Justicia,142.0
4,15,Universidad,33418,16913.0,1.975877,9.006094,0.083812,0.386598,0.529590,352.500616,43.678945,47.996165,30.031128,108.875163,34.142306,32.102460,Universidad,143.0

In [7]:
# Vamos a revisar el que no tiene valor
data_sociodem[data_sociodem["geo_barrio"].isna()]

,dem_CodBarrio,dem_Barrio,dem_PobTotal,dem_NumViviendas,dem_TamanoMedioDelHogar,dem_TasaDeParo,dem_PropSinEstudios,dem_PropSinEstudiosUniversitarios,dem_PropConEstudiosUniversitarios,dem_Densidad_(Habit/Ha),dem_EdadMedia,dem_Indice_de_juventud,dem_Indice_de_dependencia,dem_Indice_de_estructura_de_la_poblacion_activa,dem_Indice_de_reemplazo_de_la_poblacion_activa,dem_Proporcion_de_nacidos_fuera_de_Espana,geo_barrio,geo_id
13,31,Retiro,33767,14782.0,2.284332,7.657462,0.090893,0.402921,0.506187,445.327867,47.625329,41.131498,55.122198,79.367172,38.803621,15.894216,NaN,NaN

In [8]:
# El retiro no tiene valor por algun motivo. Vamos a ver cual se ha quedado huerfano
data_geo[~data_geo["name"].isin(data_sociodem.geo_barrio.unique())]

    id      name                                          st_astext  level_id
69  70  Pac√≠fico  MULTIPOLYGON(((-3.67822252305018 40.4074660186...         3

In [9]:
# Macheamos a mano
data_sociodem.loc[data_sociodem["dem_CodBarrio"] == 31, "geo_barrio"] = "Pac√≠fico"
data_sociodem.loc[data_sociodem["dem_CodBarrio"] == 31, "geo_id"] = 70
data_sociodem.head()

,dem_CodBarrio,dem_Barrio,dem_PobTotal,dem_NumViviendas,dem_TamanoMedioDelHogar,dem_TasaDeParo,dem_PropSinEstudios,dem_PropSinEstudiosUniversitarios,dem_PropConEstudiosUniversitarios,dem_Densidad_(Habit/Ha),dem_EdadMedia,dem_Indice_de_juventud,dem_Indice_de_dependencia,dem_Indice_de_estructura_de_la_poblacion_activa,dem_Indice_de_reemplazo_de_la_poblacion_activa,dem_Proporcion_de_nacidos_fuera_de_Espana,geo_barrio,geo_id
0,11,Palacio,23593,11583.0,2.036864,10.309215,0.095704,0.391468,0.512828,160.506857,45.781100,41.233620,36.045439,85.139319,32.591623,26.278981,Palacio,139.0
1,12,Embajadores,47048,22564.0,2.085091,10.658808,0.135393,0.430405,0.434202,455.131010,42.694610,60.804723,28.206665,108.044674,38.643068,36.554157,Embajadores,124.0
2,13,Cortes,10771,5449.0,1.976693,8.076921,0.074405,0.368364,0.557231,181.981221,44.779547,42.699115,31.497986,96.426859,28.985507,34.026553,Cortes,135.0
3,14,Justicia,18021,8856.0,2.034892,8.017261,0.065683,0.360603,0.573714,243.720022,44.090422,50.194553,30.823956,96.589125,40.457256,31.219133,Justicia,142.0
4,15,Universidad,33418,16913.0,1.975877,9.006094,0.083812,0.386598,0.529590,352.500616,43.678945,47.996165,30.031128,108.875163,34.142306,32.102460,Universidad,143.0

In [10]:
# Formateamos DF para mayor facilidad a la hora de cargar en BBDD
data_sociodem = data_sociodem.drop(['dem_CodBarrio', 'dem_Barrio', 'geo_barrio'], axis=1)
data_sociodem.head()

,dem_PobTotal,dem_NumViviendas,dem_TamanoMedioDelHogar,dem_TasaDeParo,dem_PropSinEstudios,dem_PropSinEstudiosUniversitarios,dem_PropConEstudiosUniversitarios,dem_Densidad_(Habit/Ha),dem_EdadMedia,dem_Indice_de_juventud,dem_Indice_de_dependencia,dem_Indice_de_estructura_de_la_poblacion_activa,dem_Indice_de_reemplazo_de_la_poblacion_activa,dem_Proporcion_de_nacidos_fuera_de_Espana,geo_id
0,23593,11583.0,2.036864,10.309215,0.095704,0.391468,0.512828,160.506857,45.781100,41.233620,36.045439,85.139319,32.591623,26.278981,139.0
1,47048,22564.0,2.085091,10.658808,0.135393,0.430405,0.434202,455.131010,42.694610,60.804723,28.206665,108.044674,38.643068,36.554157,124.0
2,10771,5449.0,1.976693,8.076921,0.074405,0.368364,0.557231,181.981221,44.779547,42.699115,31.497986,96.426859,28.985507,34.026553,135.0
3,18021,8856.0,2.034892,8.017261,0.065683,0.360603,0.573714,243.720022,44.090422,50.194553,30.823956,96.589125,40.457256,31.219133,142.0
4,33418,16913.0,1.975877,9.006094,0.083812,0.386598,0.529590,352.500616,43.678945,47.996165,30.031128,108.875163,34.142306,32.102460,143.0

In [11]:
data_sociodem.columns = ["pob_total", "count_households", "avg_size_home", "unemployment_rate", "prop_without_studies", "prop_without_university_studies", "prop_with_university_studies", "density", "avg_age", "index_youth", "index_dependency", "index_active_population", "index_replacement_active_population", "prop_born_outside", "geo_id"]
data_sociodem.head()

,pob_total,count_households,avg_size_home,unemployment_rate,prop_without_studies,prop_without_university_studies,prop_with_university_studies,density,avg_age,index_youth,index_dependency,index_active_population,index_replacement_active_population,prop_born_outside,geo_id
0,23593,11583.0,2.036864,10.309215,0.095704,0.391468,0.512828,160.506857,45.781100,41.233620,36.045439,85.139319,32.591623,26.278981,139.0
1,47048,22564.0,2.085091,10.658808,0.135393,0.430405,0.434202,455.131010,42.694610,60.804723,28.206665,108.044674,38.643068,36.554157,124.0
2,10771,5449.0,1.976693,8.076921,0.074405,0.368364,0.557231,181.981221,44.779547,42.699115,31.497986,96.426859,28.985507,34.026553,135.0
3,18021,8856.0,2.034892,8.017261,0.065683,0.360603,0.573714,243.720022,44.090422,50.194553,30.823956,96.589125,40.457256,31.219133,142.0
4,33418,16913.0,1.975877,9.006094,0.083812,0.386598,0.529590,352.500616,43.678945,47.996165,30.031128,108.875163,34.142306,32.102460,143.0

In [12]:
data_sociodem.to_csv("./SocioDem_Geo.csv")